# Working With Linear Systems in Python With `scipy.linalg`

## Getting Started With `scipy.linalg`

## Working With Vectors and Matrices Using NumPy

In [ ]:
import numpy as np

In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A
# Expected:
# array([[1, 2],
#        [3, 4],
#        [5, 6]])

In [ ]:
A.dtype
# Expected:
# dtype('int64')

In [ ]:
A = np.array([[1.0, 2], [3, 4], [5, 6]])
A
# Expected:
# array([[1., 2.],
#        [3., 4.],
#        [5., 6.]])

In [ ]:
A.dtype
# Expected:
# dtype('float64')

In [ ]:
A.shape
# Expected:
# (3, 2)

In [ ]:
A.T
# Expected:
# array([[1., 3., 5.],
#        [2., 4., 6.]])

In [ ]:
v = np.array([1, 2, 3])
v
# Expected:
# array([1, 2, 3])

In [ ]:
v.shape
# Expected:
# (3,)

In [ ]:
v = np.array([[1, 2, 3]])
v.shape
# Expected:
# (1, 3)

In [ ]:
v = np.array([[1], [2], [3]])
v.shape
# Expected:
# (3, 1)

In [ ]:
v = np.array([1, 2, 3]).reshape(3, 1)
v.shape
# Expected:
# (3, 1)

In [ ]:
v = np.array([1, 2, 3]).reshape(-1, 1)
v.shape
# Expected:
# (3, 1)

### Using Convenience Functions to Create Arrays

In [ ]:
import numpy as np

np.zeros((3, 2))
# Expected:
# array([[0., 0.],
#        [0., 0.],
#        [0., 0.]])

In [ ]:
np.ones((2, 3))
# Expected:
# array([[1., 1., 1.],
#        [1., 1., 1.]])

In [ ]:
np.random.rand(3, 2)

In [ ]:
np.random.randn(3, 2)

### Performing Operations on NumPy Arrays

In [ ]:
import numpy as np

10 * np.ones((2, 2))
# Expected:
# array([[10., 10.],
#        [10., 10.]])

In [ ]:
A = 10 * np.ones((2, 2))
B = np.array([[2, 2], [5, 5]])
A * B
# Expected:
# array([[20., 20.],
#        [50., 50.]])

In [ ]:
A = np.array([[1, 2], [3, 4]])
v = np.array([[5], [6]])
A @ v
# Expected:
# array([[17],
#        [39]])

In [ ]:
A = np.array([[1, 2], [3, 4]])
v = np.array([[5], [6]])
np.dot(A, v)
# Expected:
# array([[17],
#        [39]])

## Using `scipy.linalg.solve()` to Solve Linear Systems

### Using `scipy.linalg.solve()`

In [ ]:
import numpy as np
from scipy import linalg

A = np.array(
    [
        [3, 2],
        [2, -1],
    ]
)
b = np.array([12, 1]).reshape((2, 1))
x = linalg.solve(A, b)
x
# Expected:
# array([[2.],
#        [3.]])

## Solving a Practical Problem: Building a Meal Plan

In [ ]:
import numpy as np
from scipy import linalg

A = np.array(
    [
        [1, 9, 2, 1, 1],
        [10, 1, 2, 1, 1],
        [1, 0, 5, 1, 1],
        [2, 1, 1, 2, 9],
        [2, 1, 2, 13, 2],
    ]
)
b = np.array([170, 180, 140, 180, 350]).reshape((5, 1))
x = linalg.solve(A, b)
x
# Expected:
# array([[10.],
#        [10.],
#        [20.],
#        [20.],
#        [10.]])