**How to Write Conditional Expressions With NumPy where()**

In [1]:
import numpy as np

test_array = np.array(
    [
        [3.1688358, 3.9091694, 1.66405549, -3.61976783],
        [7.33400434, -3.25797286, -9.65148913, -0.76115911],
        [2.71053173, -6.02410179, 7.46355805, 1.30949485],
    ]
)

np.where(test_array < 0, test_array * -1, test_array)

array([[3.1688358 , 3.9091694 , 1.66405549, 3.61976783],
       [7.33400434, 3.25797286, 9.65148913, 0.76115911],
       [2.71053173, 6.02410179, 7.46355805, 1.30949485]])

In [2]:
np.abs(test_array)

array([[3.1688358 , 3.9091694 , 1.66405549, 3.61976783],
       [7.33400434, 3.25797286, 9.65148913, 0.76115911],
       [2.71053173, 6.02410179, 7.46355805, 1.30949485]])

In [3]:
test_array < 0

array([[False, False, False,  True],
       [False,  True,  True,  True],
       [False,  True, False, False]])

In [4]:
test_array = np.random.uniform(low=-10, high=10, size=(3, 4))
test_array

array([[-0.68506937,  5.66604672,  0.58421751,  4.8946752 ],
       [-4.2481913 , -1.13216087,  0.63353423,  2.63621566],
       [-1.11812408,  7.15968405, -7.5696163 , -2.37413593]])

**How to Use Multiple Conditional Expressions**

In [ ]:
# Warning - this code will fail

import numpy as np

test_array = np.array(
    [
        [3.1688358, 3.9091694, 1.66405549, -3.61976783],
        [7.33400434, -3.25797286, -9.65148913, -0.76115911],
        [2.71053173, -6.02410179, 7.46355805, 1.30949485],
    ]
)

np.where(
    (test_array > -2) and (test_array < 3),
    test_array * -1,
    test_array,
)

In [6]:
test_array > -2

array([[ True,  True,  True, False],
       [ True, False, False,  True],
       [ True, False,  True,  True]])

In [7]:
test_array < 3

array([[False, False,  True,  True],
       [False,  True,  True,  True],
       [ True,  True, False,  True]])

In [8]:
(test_array > -2) & (test_array < 3)

array([[False, False,  True, False],
       [False, False, False,  True],
       [ True, False, False,  True]])

In [9]:
np.where(
    (test_array > -2) & (test_array < 3),
    test_array * -1,
    test_array,
)

array([[ 3.1688358 ,  3.9091694 , -1.66405549, -3.61976783],
       [ 7.33400434, -3.25797286, -9.65148913,  0.76115911],
       [-2.71053173, -6.02410179,  7.46355805, -1.30949485]])

In [10]:
np.where(
    (test_array <= -2) | (test_array >= 3),
    test_array * -1,
    test_array,
)

array([[-3.1688358 , -3.9091694 ,  1.66405549,  3.61976783],
       [-7.33400434,  3.25797286,  9.65148913, -0.76115911],
       [ 2.71053173,  6.02410179, -7.46355805,  1.30949485]])

**Question 1 Solutions**

In [12]:
# Solution 1_1

question_1 = np.arange(
    -10,
    10,
).reshape(5, 4)

np.where(
    (question_1 < 0) | (question_1 % 2 == 0),
    9,
    question_1,
)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 1],
       [9, 3, 9, 5],
       [9, 7, 9, 9]])

In [13]:
# Solution 1_2

np.where(
    (question_1 < 0) & (question_1 % 2 != 0),
    np.square(question_1),
    question_1,
)

array([[-10,  81,  -8,  49],
       [ -6,  25,  -4,   9],
       [ -2,   1,   0,   1],
       [  2,   3,   4,   5],
       [  6,   7,   8,   9]])

In [14]:
# Solution 1_3

np.where(
    ((question_1 > 3) & (question_1 < 7)) | (question_1 == 1),
    -10,
    question_1 - 1,
)

array([[-11, -10,  -9,  -8],
       [ -7,  -6,  -5,  -4],
       [ -3,  -2,  -1, -10],
       [  1,   2, -10, -10],
       [-10,   6,   7,   8]])

**How to Use Array Broadcasting in Conditional Expressions**

In [25]:
booking_data = np.array(
    [
        [np.nan, np.nan, 1],
        [1, 1, np.nan],
        [1, np.nan, 1],
        [1, 1, 1],
    ]
)

In [16]:
booking_data.shape

(4, 3)

In [17]:
meal_prices = np.array([5.1, 8.2, 20.3]).reshape(1, 3)
no_charge = 0

In [18]:
booking_prices = np.where(booking_data == 1, meal_prices, no_charge)
booking_prices

array([[ 0. ,  0. , 20.3],
       [ 5.1,  8.2,  0. ],
       [ 5.1,  0. , 20.3],
       [ 5.1,  8.2, 20.3]])

**Question 2 Solutions**

In [20]:
# Solution 2_1

question_2 = np.arange(12).reshape(3, 4)  # Shape (3, 4)

high = "HIGH"
low = "LOW"

np.where(question_2 > 6, high, low)

array([['LOW', 'LOW', 'LOW', 'LOW'],
       ['LOW', 'LOW', 'LOW', 'HIGH'],
       ['HIGH', 'HIGH', 'HIGH', 'HIGH']], dtype='<U4')

In [21]:
# Solution 2_2

high = np.array(["HIGH"])  # Shape (1,)
low = np.array(["LOW"])  # Shape (1,)

np.where(question_2 > 6, high, low)

array([['LOW', 'LOW', 'LOW', 'LOW'],
       ['LOW', 'LOW', 'LOW', 'HIGH'],
       ['HIGH', 'HIGH', 'HIGH', 'HIGH']], dtype='<U4')

In [22]:
# Solution 2_3

high = np.array(["HIGH", "HIGH", "HIGH", "HIGH"])  # Shape (4,)
low = np.array(["LOW"])  # Shape (1,)

np.where(question_2 > 6, high, low)

array([['LOW', 'LOW', 'LOW', 'LOW'],
       ['LOW', 'LOW', 'LOW', 'HIGH'],
       ['HIGH', 'HIGH', 'HIGH', 'HIGH']], dtype='<U4')

**How Not to Use np.where() - A Final Quirk**

In [23]:
import numpy as np

mostly_zeroes = np.array([[9, 0, 0], [0, 8, 5], [0, 0, 7]])
np.where(mostly_zeroes != 0)

(array([0, 1, 1, 2]), array([0, 1, 2, 2]))

In [24]:
np.nonzero(mostly_zeroes)

(array([0, 1, 1, 2]), array([0, 1, 2, 2]))